//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Table {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Table() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Table", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivnosti.
        /// </summary>
        internal static string Table_Action {
            get {
                return ResourceManager.GetString("Table.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijent.
        /// </summary>
        internal static string Table_Client {
            get {
                return ResourceManager.GetString("Table.Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum zaposlenja.
        /// </summary>
        internal static string Table_Date {
            get {
                return ResourceManager.GetString("Table.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-pošta.
        /// </summary>
        internal static string Table_Email {
            get {
                return ResourceManager.GetString("Table.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string Table_FirstName {
            get {
                return ResourceManager.GetString("Table.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        internal static string Table_LastName {
            get {
                return ResourceManager.GetString("Table.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titula.
        /// </summary>
        internal static string Table_Position {
            get {
                return ResourceManager.GetString("Table.Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voditelj.
        /// </summary>
        internal static string Table_TeamLeader {
            get {
                return ResourceManager.GetString("Table.TeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string Table_Title {
            get {
                return ResourceManager.GetString("Table.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijenti.
        /// </summary>
        internal static string Table_Title_Clients {
            get {
                return ResourceManager.GetString("Table.Title.Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekti.
        /// </summary>
        internal static string Table_Title_Projects {
            get {
                return ResourceManager.GetString("Table.Title.Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voditelji timova.
        /// </summary>
        internal static string Table_Title_TeamLeader {
            get {
                return ResourceManager.GetString("Table.Title.TeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Djelatnici.
        /// </summary>
        internal static string Table_Title_Workers {
            get {
                return ResourceManager.GetString("Table.Title.Workers", resourceCulture);
            }
        }
    }
}
